### ISSUE TITLE
Upload a teamspeak avatar containing more info

### ISSUE THREAD

**Issue by fkaa** [hivecom/pokebot#17]
Upload an avatar of maybe the current playlist and other information that cant fit in the nickname or description. Can probably have some fun with gif (/dʒɪf/) or even SVG as well..

Probably a good idea to make it an optional feature (in rust terms) since it's a very standalone feature.

Relevant crates:
* Drawing - https://lib.rs/crates/raqote https://lib.rs/crates/piet
* Image encoding - https://lib.rs/crates/image

**Comment by kilmanio** [comment]
Imagine not being able to say gif (/ɡɪf/) properly.

**Comment by fkaa** [comment]
Closing because lack of interest :=)
