### ISSUE TITLE
Add an option to the config file to disable the web server

### ISSUE THREAD

**Issue by Jokler** [hivecom/pokebot#35]
**Is your feature request related to a problem? Please describe.**
Not everyone running the bot is interested in supporting a web server with API too.

**Describe the solution you'd like**
It should be possible to set a feature flag to remove the web server components at build time.

**Comment by Jokler** [comment]
Making this an option in the cofiguration file would probably be simpler overall.

**Comment by kilmanio** [comment]
working on this
