### ISSUE TITLE
Bot doesn't play music when it joins a channel

### ISSUE THREAD

**Issue by TheGreatestJannet** [hivecom/pokebot#49]
**Describe the bug**
The bot joins the channel and doesn't play any music.

**To Reproduce**

1. Poke the bot with the play command. I'm using play https://www.youtube.com/watch?v=djV11Xbc914
2. New bot joins and doesn't play any music

**Expected behavior**
I expect the bot to join the channel and play music.

**Additional context**
I have gstreamer1.0-plugins-good  installed and this is the console log:
```
18:29:50.751 INFO tokio-runtime-worker-2[3045056160] src/audio_player.rs:89 - Creating audio player
18:29:54.790 INFO tokio-runtime-worker-2[3045056160] src/audio_player.rs:208 - Setting volume: 0.5 -> -15.05149978319906 dB                                                                                                                  
18:29:54.790 INFO tokio-runtime-worker-2[3045056160] src/bot/music.rs:265 - Setting TeamsSpeak nickname to 🎵 MusicBot (50%)                                                                                                                 
18:29:54.791 DEBUG gstreamer polling[3011460768] src/audio_player.rs:334 - Polling GStreamer
18:29:54.791 DEBUG gstreamer polling[3011460768] src/audio_player.rs:365 - Pipeline transitioned from Null to Ready, with VoidPending pending
```

**Comment by Jokler** [comment]
Okay, in that case I misunderstood what you were doing, you poke the bot to get it to join, then you can use commands in chat, try `!help`.

**Comment by Jokler** [comment]
This should really be mentioned in the readme, too.

**Comment by TheGreatestJannet** [comment]
Thank you after using the commands in chat it works perfectly. Thank you for your hard work on the bot!
