### ISSUE TITLE
Use Cow instead

### ISSUE THREAD

**Issue by fkaa** [hivecom/pokebot#55]
https://github.com/Mavulp/pokebot/blob/3575ac579cdcc5a9fa3ffec84952a634d1d7deaf/src/web_server.rs#L53

**Comment by zealsprince** [comment]
I don't get what you want from me. What is _cow_.

**Comment by Jokler** [comment]
A [`Cow<'_, str>`](https://doc.rust-lang.org/std/borrow/enum.Cow.html) can be [`String`](https://doc.rust-lang.org/alloc/string/struct.String.html) or [`&str`](https://doc.rust-lang.org/std/primitive.str.html), whichever one is needed.

**Comment by zealsprince** [comment]
Oh that's pretty neat. Didn't know about this and thought it was just some inside joke I missed :)

**Comment by Jokler** [comment]
Closed because no one responded for 26 days.
