### ISSUE TITLE
Play Local Music

### ISSUE THREAD

**Issue by TheGreatestJannet** [hivecom/pokebot#61]
**Is your feature request related to a problem? Please describe.**
It would be nice if the MusicBot would be able to play local music stored on device's hard drive.

**Describe the solution you'd like**
A command to browse the music in a folder and play it. Personally I'd like it play FLAC files but other format such as MP3 would be good too!

**Comment by Jokler** [comment]
Do you have an example of what browsing the files would look like?

**Comment by TheGreatestJannet** [comment]
Either this could be done from the web interface. This would make it much easier to navigate or a command such as `!view` could be added which would show all the folders in the Music folder on the hard drive and then `!view Lionel Richi` to view the files in that folder. Then using `!add Lionel Richi/Easy.flac` to play it. Not sure how the folder name with spaces would work maybe use “”. Of course if you have a better idea feel free to post it! Thanks again for your hard work on the bot!

**Comment by Jokler** [comment]
Spaces shouldn't be a problem as long as the command only has one argument, I don't think `!add` is a good idea though since that is already used for links. Unless you want something like `!add local:Lionel Richi/Easy.flac` another command would be better.

**Comment by TheGreatestJannet** [comment]
That is true either we could use `!add local:Lionel Richi/Easy.flac` or we could add another command such as `!local` or something like that. Seeing as it is adding it to the queue just like an online source I thought it might be a good idea to use one command for everything but I understand this could be an issue.

**Comment by Jokler** [comment]
Just to give you an update:
It is very easy to add playback for local files but I don't know what the best way to collect the metadata would be yet. As a result I have stopped working on it for a while now since it is not that important to me personally.

**Comment by TheGreatestJannet** [comment]
That’s fine! What do you mean by metadata? Isn’t just putting playing filename good enough? Although it would be nice to have track length etc it’s not essential in my opinion.

**Comment by Jokler** [comment]
It is not essential but if I do add it I would like it to at least have some amount of quality.

**Comment by Jokler** [comment]
It ended up being easier than I expected, sorry I didn't look into it earlier. :)

**Comment by TheGreatestJannet** [comment]
That’s fine! Thanks a lot for implementing it!

**Comment by Jokler** [comment]
I will probably implement #80 with fuzzy finding soon so that the `!search` command will search local files first and then youtube. :)

**Comment by TheGreatestJannet** [comment]
Thanks! How do I add the local folder? I can't see anything new in the config.toml.

**Comment by Jokler** [comment]
I kind of forgot about the example in the config file.
It is updated now.

**Comment by Jokler** [comment]
Use `!add file://relative/path/to/file.mp3` for now.

**Comment by TheGreatestJannet** [comment]
Thanks a lot for implementing this. It works perfectly! Hopefully search is added too as without it, users who don’t know my file system will have a hard time finding tracks!

Thanks again!
