### ISSUE TITLE
Default channel does not work

### ISSUE THREAD

**Issue by maltechx** [hivecom/pokebot#62]
**Describe the bug**
Setting channel ID or name in config does not work. The bot does not join the specified channel, but still joining the lobby.

**To Reproduce**
Set a different channel ID or name than lobby and start the bot.

**Expected behavior**
The bot should join the specified channel.

**Comment by Jokler** [comment]
The default channel has the same format as it does in the bookmarks in the normal TeamSpeak client.
You can set the default channel in TeamSpeak first and copy it from there if you want to make sure you get it right.

This should maybe be mentioned in a comment in the config file. :p

**Comment by maltechx** [comment]
Thank you. This should indeed be mentioned.

**Comment by Jokler** [comment]
Resolved in 161c8ab.
