### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by dolanske** [hivecom/pokebot#66]
Should get updated.

**Comment by zealsprince** [comment]
@kilmanio

**Comment by dolanske** [comment]
Nice job team let's get this fixed

**Comment by kilmanio** [comment]
#64 #

**Comment by dolanske** [comment]
Works on my machine 👌 kilmanio

**Comment by zealsprince** [comment]
Doesnt work on mine. Reopening.

Edit: Formatting.

**Comment by dolanske** [comment]
Fixing #66 should fix it.
Edit: added dot
Edit2: fixed dod > dot
