### ISSUE TITLE
Gstreamer dash error message

### ISSUE THREAD

**Issue by TheGreatestJannet** [hivecom/pokebot#74]
**Describe the bug**
Gstreamer error when playing a video

**To Reproduce**
Add the following video: https://www.youtube.com/watch?v=uj97kISm1nc
See error message in console

**Expected behavior**
It should play the video without any errors

**Additional context**
ERROR unnamed[3041914752] src/audio_player.rs:373 - Received error from bus, musicbot: MusicBot, master: PokeBot, debug: Some("gstdecodebin2.c(4640): gst_decode_bin_expose (): /GstPipeline:TeamSpeak Audio Player/GstDecodeBin:decode bin:\nno suitable plugins found:\nMissing decoder: application/dash+xml (application/dash+xml)\n"), error: Your GStreamer installation is missing a plug-in., source: Some(GString(Foreign(0xaf521bc0, 59)))

Do I need to install a plugin to decode dash? I have base, good and ugly installed.

**Comment by Jokler** [comment]
I can't reproduce it on that link so I think YouTube is providing different formats for you but I got the same error on this link: http://www-itec.uni-klu.ac.at/ftp/datasets/mmsys12/RedBullPlayStreets/redbull_4s/RedBullPlayStreets_4s_isoffmain_DIS_23009_1_v_2_1c2_2011_08_30.mpd  

It looks like `gst-plugins-bad` includes the required plugin though, maybe that is enough to fix the error for you?

**Comment by TheGreatestJannet** [comment]
What distro are you on? I'm on Raspbian and I have the package `gstreamer1.0-plugins-bad` but I still get the same error. `gst-plugins-bad` isn't a package for me

**Comment by TheGreatestJannet** [comment]
Yep installing gstreamer1.0-plugins-bad worked thank you!
